### PR TITLE
Remove outdated frontier feature

### LINKED ISSUE #47: frontier feature outdated?
I'm looking for a component to build a Squid proxy (for CVMFS).

I gave a look at frontier feature, but it seems to be a bit outdated:
* uses PKG_ARCH_GLITE while not in the template-library-grid
* uses explicit frontier-squid rpm version number (not yum based spma)

These are easy to fix, but is this feature still maintained? Would we better use something else?

Thanks n advance,

Pierre

### PR DESCRIPTION
**Pull request by jrha**
Feature is currently broken, so remove it, new one should be written to replace it with metaconfig.

Closes #47.

### CODE REVIEW

**Comment by jouvin** [comment]
I tend to disagree with this PR. We cannot just delete broken pieces of code, we need to fix it (this is not the configuration module that we don't need anymore)! I would suggest closing this PR and assigning the issue to the next release.

**Comment by jrha** [comment]
We can delete it and re-add it, but I'd rather not ship it in the release if we know it is broken (which we do).

**Comment by jrha** [comment]
If you prefer, I can create a release branch without this broken feature.

**Comment by jouvin** [comment]
Probably, you are right, we can remove it as it is broken and open an issue about the need to fix it with a reference to the commit removing it.

**Comment by jrha** [comment]
Issue created, please merge if you are happy.

**Pull request merged**
