### PR TITLE
Add new CVMFS repository

### PR DESCRIPTION
**Pull request by Pansanel**
Add the France Grilles (IN2P3) repository

### CODE REVIEW

**Comment by jouvin** [comment]
Basically looks good but why not to use `metaconfig` rather than `filecopy`?

**Comment by Pansanel** [comment]
I simply use the same code as for the other CVM repositories. Pierre will submit a new code to factorize the client.pan code. I will suggest him to use metaconfig.

**Comment by jouvin** [comment]
@Pansanel is this PR still needed after #72? In this case we should have it in 16.10.

**Comment by Pansanel** [comment]
It is ok for me. I merge.

**Pull request closed without merging**
