### PR TITLE
Add templates for several Xeon Phi

### PR DESCRIPTION
**Pull request by jouvin**

### CODE REVIEW

**Comment by jrha** [comment]
Were these generated with `ark2pan`?

**Comment by jouvin** [comment]
No idea. I found them at GRIF!

**Comment by jrha** [comment]
@jouvin I generated the same templates (and a few more) with `ark2pan` and updated your branch

**Comment by jrha** [comment]
I've removed the Knights Corner Phi from this PR as they are only available as co-processors and don't belong in our CPU tree. Knights Landing onwards are available in host-processor form, so can be included.

**Pull request merged**
