### PR TITLE
Add gpt label support

### PR DESCRIPTION
**Pull request by Pansanel**
It permit to disable logical / extended partitions when using gpt partition tables.

### CODE REVIEW

**Comment by jrha** [comment]
Have you considered making `gpt` the default?

**Comment by Pansanel** [comment]
It makes sense to use gpt by default (many servers have 2TB or bigger hard drive), but in this case, Quattor users have to redefine the variable for each host where they want to keep msdos. It may be safer to discuss about this on the mailing list.

**Comment by jrha** [comment]
We've been using only gpt for years now with no issues on hardware up to eight years old, maybe we should have a discussion about it, it's basically only SSDs that are smaller than 2TB in our infrastructure now.

**Comment by jouvin** [comment]
I'd tend to agree with @jrha : we can probably use it as a default mentionning in the documentation what to do to use msdos label in case the default is a problem. I am convinced that almost nobody will notice the default change...

**Comment by jrha** [comment]
I'm quite happy to put **bold words** in the release notes :smile:

**Comment by jrha** [comment]
@Pansanel, please make gpt the default, I will ensure I make it clear in the release notes that this change has happened and what is required to switch back to msdos.

**Pull request merged**
