### PR TITLE
adding support for dockers

### PR DESCRIPTION
**Pull request by sartiran**
tentatively proposing for a PR the templates used at grif for configuring docker. This setup is running at GRIF_LAL for some development machines and at GRIF_LLR for some docker based services.

### CODE REVIEW

**Comment by stdweird** [comment]
@sartiran can you remove the `.svn` files that you also pushed?

**Comment by sartiran** [comment]
Yep. Sorry. Done.

**Comment by jrha** [comment]
@sartiran can you squash the two commits together? Then the svn files will really be gone!

**Comment by jrha** [comment]
@alahiff any comments?

**Comment by sartiran** [comment]
OK. Wait. To avoid making mess with squashed commits, I close and re-open the PR (doing a single commit w/o svn files)

**Pull request closed without merging**
