### PR TITLE
Remove Xeon Phi and add new Intel CPUs from ARK

### PR DESCRIPTION
**Pull request by jrha**
* Remove Xeon Phi, which were accidentally added in the previous bulk import from ARK, but make no sense for us AFAIK.
* Add new processor definitions from ARK since previous sync.

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha wrt the phi, new KNL run standalone as regular x86 server. i'll readd it if we ever buy some 😄

**Comment by stdweird** [comment]
@jrha milestone?

**Comment by jrha** [comment]
*bump*

**Comment by jrha** [comment]
@stdweird are you happy to merge?

**Comment by stdweird** [comment]
@jrha sure. and if you find the time, can you make a PR to update with latest intel cpus? 😄

**Comment by jrha** [comment]
Sure, if ARK still supports the export functionality!

**Pull request merged**
