### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by sartiran**
tentatively proposing for a PR the templates used at grif for configuring docker. This setup is running at GRIF_LAL for some development machines and at GRIF_LLR for some docker based services. (PR re-done w/o svn files)

### CODE REVIEW

**Comment by jrha** [comment]
Replaces #67

**Comment by jrha** [comment]
@alahiff, any comments on this one?

**Comment by alahiff** [comment]
There seems to be an assumption here that by default Docker engine will make use of `/etc/sysconfig/docker`. However, on SL7 at least, this is not the case (e.g. with Docker 1.11 or any other recent version). Being able to specify options for the Docker daemon is quite important, so it would be good if this could be fixed. If you really want to use `/etc/sysconfig/docker`, then you could add a file `/etc/systemd/system/docker.service.d/override.conf` containing, for example:
```
[Service]
EnvironmentFile=-/etc/sysconfig/docker
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// $OPTIONS
```

where OPTIONS is defined in `/etc/sysconfig/docker`.

**Comment by sartiran** [comment]
Hi,
indeed this is something I've forgotten to mention: at GRIF we are currently running dockers only on SL6 servers. And these templates deal with configuring docker on sl6 only. Using docker on sl6 is not optimal and we plan to test it on sl7 asap. Then we will be able to write a sl7 compatible config.
For the moment, I'll be happy to introduce any sl7 compliant way to pass parameters to the docker service... but I've no way to test it.

**Comment by alahiff** [comment]
I can help test on SL7 if necessary.

Also, from my point of view it would be better if the backup script and in particular pipework were separate features as not everyone will need them. I know they're just including some scripts (and a cron for the case of backup), but I like the idea of being able to pick and choose exactly what should be installed rather than having lots of things grouped together.

**Comment by sartiran** [comment]
the backup feature can be activated by setting the DOCKER_BACKUP variable (which is false by default), and I can do the same for pipework. Or would you prefer a completely different reorganization of templates? (the creation of features/pipework and features/docker-backup?)

**Comment by alahiff** [comment]
Ideally I would like to see something like features/docker/pipework & features/docker/backup, as they are independent features.

(Sorry about this, it's just that one of the things I get annoyed with in Quattor is that so many of the "official" templates combine too many different things together when they should really be kept completely separate).

**Comment by jrha** [comment]
I completely agree about the template libraries, they are a long way from the pick-and-choose libraries that they should be.

**Comment by stdweird** [comment]
@alahiff you can generate those units with `ncm-systemd`. we could also add an option to `ncm-systemd` to create a sysconfig entry from a systemd configuration, so when you run ncm-systemd on el6, you get the sysconfig entry, and on el7 you get a clean unit instead this trickery with the `EnvironmentFile`

**Comment by alahiff** [comment]
@stdweird is there an example showing how to use ``ncm-systemd`` anywhere?

**Comment by stdweird** [comment]
@alahiff for systemd units? sure (well, i'll have a look). but for magic sysconfig generation, no, that would be a feature request :smile:  i'll have a look for examples

**Comment by alahiff** [comment]
@stdweird yes, for systemd units. I had a look some time ago but couldn't find any.

**Comment by stdweird** [comment]
@alahiff 
* ncm-systemd unittests: https://github.com/quattor/configuration-modules-core/blob/master/ncm-systemd/src/test/resources/unitfile_config.pan 
* some of our own templates
 * ugly ceph-fuse mounts via systemd https://github.com/stdweird/quattor-SCDB-ugent/blob/master/cfg/services/common/opennebula/ceph_fuse.pan#L34 (but a good example for unittfiles :smile: )
```
# cat /etc/systemd/system/ceph-fuse-ONE.service 

[Install]
WantedBy=multi-user.target


[Service]
ExecStart=/usr/bin/ceph-fuse --id=cephfs /var/lib/one/datastores/0
ExecStop=/bin/umount /var/lib/one/datastores/0
Restart=on-failure
RestartSec=120
Type=forking

[Unit]
After=network.target

Before=libvirtd.service

ConditionPathIsDirectory=/var/lib/one/datastores/0

Description=Ceph fuse libvirt/ONE mount
Requires=network.target


```
 * ceph mds tuning: the mds process are pinned on one numa node https://github.com/stdweird/quattor-SCDB-ugent/blob/master/cfg/clusters/gigalith/site/ceph/cluster/tuning_mds.pan
(it generates on a E5-2623 v3 (haswell with CoD and HT)
```
[root@mds01 ~]# cat /etc/systemd/system/ceph-mds\@.service.d/quattor.conf 

[Service]
CPUAffinity=
CPUAffinity=1 9 3 11 5 13 7 15


```

**Comment by sartiran** [comment]
Hi,
I've rearranged the templates to make each sub-feature (service, backup, pipework) independent (plus a config template which groups everything). I've created a os-dependent part of the service template, for sl6, where I've put the sysconfig and chkconfig parts. In a corresponding el7 part one should put the systemd configuration. I currenltly have no el7 machines so, if someone else would like to create it and test it (otherwise I can just put a "not yet implemented" and review the stuff as soon as I'll migrate my docker services on centos7).

**Comment by jouvin** [comment]
@sartiran Quattor is great :-) there is no need to have EL6/EL7 specific templates for the init/systemd config. `ncm-chkconfig` when used on a EL7 machine (with EL7 OS templates) configures systemd instead of init (using the same config).

**Comment by sartiran** [comment]
Yep. Actually the el6/el7 split was more like for the sysconfig part. It was suggested to use the ncm-systemd component but I wold say that it won't work with el6 (am I wrong?). So I was thinking to move the systemd part into a specific el7 template (I've put the chkconfig part for coherence). But I can do otherwise, if you prefer.

**Comment by jouvin** [comment]
`ncm-chkconfig` on EL7 manages `systemd` (not the backward compatibility with init) and it works for most things. So I would recommend keeping using it when you need to maintain a template for both EL6 and EL7.

**Comment by sartiran** [comment]
Hi, 
ok. Let's try to converge with this.
- To Michel: the point is not chkconfig but sysconfig. I need to pass arguments to the docker service. And for this I've used ncm-sysconfig. As pointed out by alahiff this works only in el6 and el7 would rather require ncm-systemd (which, as far as I know, does not work with el6). That's why I did the OS based splitting. But it is probably just my ignorance: is there a OS independent way to pass arguments to the docker service?

Regards,
Andrea

**Comment by jouvin** [comment]
@sartiran I think the easiest is to have the paramaters defined in `/etc/sysconfig` and use `ncm-systemd` to ensure that the file is loaded by `systemd` before starting the service. This is what is done by most services.

To manage the sysconfig file for Docker, I'd recommend to use `ncm-metaconfig` with a schema rather than `ncm-sysconfig` that we want to deprecate.

My other point is that you can probably used `ncm-chkconfig` on both EL6 and EL7 as it will  in fact configure `systemd` on EL7. Depending whether the standard `systemd` unit file is already configured to read a sysconfig file, you may have to do this additional configuration on EL7... (and I am not sure that in this case using the `ncm-chkconfig` interface on EL7 will work).

**Comment by jrha** [comment]
@jouvin was this PR overtaken by #105?

**Comment by jouvin** [comment]
It seems that I forgot I had a waiting PR for very long at some point and open a new one. Yes this one is completly outdated...

**Pull request closed without merging**
