### PR TITLE
New Intel network card

### PR DESCRIPTION
**Pull request by Pansanel**
The Intel X540 card is a 10Gb Base-T network adapter.

### CODE REVIEW

**Comment by jrha** [comment]
LGTM, did you obtain the name string from a running system?

**Comment by stdweird** [comment]
http://ark.intel.com/products/family/46828/Intel-10-Gigabit-Server-Adapters
there seesm to be no `-AT2`.
@jrha didn't you have a script to scrape the intel ark for cpus? maybe it works for their adapters too?

**Comment by jrha** [comment]
https://github.com/jrha/ark2pan

**Comment by jrha** [comment]
X540-AT2 is fine, it's the controller chip-set on the card.

**Pull request merged**
