### PR TITLE
Add Intel CPUs from ARK

### PR DESCRIPTION
**Pull request by jrha**
These templates have been generated from data on Server CPUs extracted from Intel's [ARK](http://ark.intel.com/search/advanced?s=t&MarketSegment=SRV) database, adding more detail than we have had in the past, but also introducing some minor changes.

There are some pieces of information that would be useful to have, but we do not support in the schema (e.g. thread count) that might be useful to have and could be added trivially.

Some backwards incompatibility has been caused by the rename of all existing CPUs to lower-case, however this is unavoidable if we wish to maintain compatibility with aquilon.

### CODE REVIEW

**Comment by jrha** [comment]
I also feel like the text in `model` would be better of under `name`, keeping `model` for the actually model number (e.g. E5-4650).

**Comment by ned21** [comment]
Do you have a script to generate these? I didn't know ARK existed - we've wanted this for a while!

**Comment by jrha** [comment]
I do! but it's not nice, the ARK data needs a bit of manual munging in Excel :see_no_evil: first
I'm playing around with [cpudb](http://cpudb.stanford.edu/) as well, but it's obviously not as complete.

**Comment by jrha** [comment]
Ok, the script is good enough now, you can find it at https://github.com/jrha/ark2pan

**Comment by brunocanning** [comment]
>I also feel like the `cpuinfo` style text in `model` would be better off under `name`, keeping model for the actual model number (e.g. E5-4650).

I agree with @jrha, I sometimes need special configuration to be included in a build if a certain model of nic, cpu, machine etc... is used. Having the `model` field equal to the actual model and equal to the part of the template declaration string between the final "/" and the ";" would be a real help when finding the relevant template and pattern matching in pan code.

**Comment by brunocanning** [comment]
Additionally, should we standardise on lowercase for the `manufacturer` field, again so it is the same as in the template declaration string?

**Comment by brunocanning** [comment]
Oh, and this is really good work BTW.

**Comment by stdweird** [comment]
LGTM

**Pull request merged**
