### PR TITLE
Move all CPUs into a manufacturer namespace and clean up the template contents

### PR DESCRIPTION
**Pull request by Pansanel**

### CODE REVIEW

**Comment by jouvin** [comment]
Could you move the files to `cpu/intel`... We decided to have a vendor namespace a long time ago, it's time to implement it!

**Comment by Pansanel** [comment]
Should I also move the old CPU to the new namespace?

**Comment by jouvin** [comment]
Would be good!

**Comment by jrha** [comment]
Thanks!

**Comment by Pansanel** [comment]
I have to update the example template before to merge this PR.

**Comment by jouvin** [comment]
Thanks, I was about to do it. Please, can you put the PR for the examples here (or reference this one in examples PR).

**Pull request merged**
