### PR TITLE
pakiti: remove SPMA  and v2 client support

### PR DESCRIPTION
**Pull request by jouvin**
Also include template code linting.

### CODE REVIEW

**Comment by jrha** [comment]
Thanks! Feel like fixing the panlint errors at the same time?

**Comment by jouvin** [comment]
I'll look at it. I had not time to look at the test result....

**Comment by jrha** [comment]
Cool, thanks!

**Comment by jouvin** [comment]
Should be ok now! I took the occasion for doing a major cleanup!

**Pull request merged**
